### ISSUE TITLE
Hash Combiners with XORing are slightly less secure

### ISSUE THREAD

**Issue by kchalkias** [ethereum/solidity-underhanded-contest#7]
I recommend this paper as a reference on the provided security against pre-image resistance when XOR-combining hashes. 
In theory it's considered less secure, as the authors claim "For any narrow-pipe functions, the sum, is not pre-image resistant".

https://eprint.iacr.org/2015/070.pdf

**Comment by d-sfounis** [comment]
What's this in reference to? Would legit love to know.

The 2022 top-3 entries did not mesh with hash combinatronics to scheme their attack vectors.

**Comment by ekpyron** [comment]
Without further details, I don't see anything to be acted upon here, so I'm closing.
